### ISSUE TITLE
Error running Kibana as non-root user

### ISSUE THREAD

**Issue by bladerunner512** [elastic/kibana-docker#143]
Kibana v6.2.1 (kibana-6.2.1-amd64.deb installed on Ubuntu 16.04)
kibana.yml: server.port: 5601   server.host: 0

Running as root is successful, change to non-root user fails:

FATAL { ValidationError: child "server" fails because [child "host" fails because ["host" must be a valid hostname], child "port" fails because ["port" must be a number]]
    at Object.exports.process (/usr/share/kibana/node_modules/joi/lib/errors.js:181:19)
    at _validateWithOptions (/usr/share/kibana/node_modules/joi/lib/any.js:651:31)
    at root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:121:23)
    at Config._commit (/usr/share/kibana/src/server/config/config.js:119:35)
    at Config.set (/usr/share/kibana/src/server/config/config.js:89:10)
    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:62:10)
    at _lodash2.default.each.child (/usr/share/kibana/src/server/config/config.js:51:14)
    at arrayEach (/usr/share/kibana/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/share/kibana/node_modules/lodash/index.js:3345:13)
    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:50:31)
    at new Config (/usr/share/kibana/src/server/config/config.js:41:10)
    at Function.withDefaultSchema (/usr/share/kibana/src/server/config/config.js:34:12)
    at KbnServer.exports.default (/usr/share/kibana/src/server/config/setup.js:9:37)
    at /usr/share/kibana/src/server/kbn_server.js:150:20
    at next (native)
    at step (/usr/share/kibana/src/server/kbn_server.js:71:191)

**Comment by bladerunner512** [comment]
error in configMap providing kibana.yml host and port values
