### ISSUE TITLE
Compose 2.1 variable substition for XPACK_SECURITY_SECURECOOKIES in kibana docker?

### ISSUE THREAD

**Issue by ctindel** [elastic/kibana-docker#53]
I have a compose 2.1 file and i'm trying to do XPACK_SECURITY_SECURECOOKIES as a variable because i need it to be false when run on my laptop locally but true when run behind an ELB that handles the ssl termination.

So I tried XPACK_SECURITY_SECURECOOKIES: "$${XPACK_SECURITY_SECURECOOKIES:-false}" under environment.  I also tried it without quotes: XPACK_SECURITY_SECURECOOKIES: $${XPACK_SECURITY_SECURECOOKIES:-false}

But I get this stack trace either way:

sa-demo-cyclops-kibana    | {"type":"log","@timestamp":"2017-10-15T07:30:53Z","tags":["fatal"],"pid":1,"level":"fatal","message":"child \"xpack\" fails because [child \"security\" fails because [child \"secureCookies\" fails because [\"secureCookies\" must be a boolean]]]","error":{"message":"child \"xpack\" fails because [child \"security\" fails because [child \"secureCookies\" fails because [\"secureCookies\" must be a boolean]]]","name":"ValidationError","stack":"ValidationError: child \"xpack\" fails because [child \"security\" fails because [child \"secureCookies\" fails because [\"secureCookies\" must be a boolean]]]\n    at Object.exports.process (/usr/share/kibana/node_modules/joi/lib/errors.js:181:19)\n    at _validateWithOptions (/usr/share/kibana/node_modules/joi/lib/any.js:651:31)\n    at root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:121:23)\n    at Config._commit (/usr/share/kibana/src/server/config/config.js:114:35)\n    at Config.set (/usr/share/kibana/src/server/config/config.js:84:10)\n    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:57:10)\n    at /usr/share/kibana/src/server/plugins/plugin_collection.js:19:12\n    at next (native)\n    at step (/usr/share/kibana/src/server/plugins/plugin_collection.js:49:191)\n    at /usr/share/kibana/src/server/plugins/plugin_collection.js:49:361"}}
sa-demo-cyclops-kibana    | FATAL { ValidationError: child "xpack" fails because [child "security" fails because [child "secureCookies" fails because ["secureCookies" must be a boolean]]]
sa-demo-cyclops-kibana    |     at Object.exports.process (/usr/share/kibana/node_modules/joi/lib/errors.js:181:19)
sa-demo-cyclops-kibana    |     at _validateWithOptions (/usr/share/kibana/node_modules/joi/lib/any.js:651:31)
sa-demo-cyclops-kibana    |     at root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:121:23)
sa-demo-cyclops-kibana    |     at Config._commit (/usr/share/kibana/src/server/config/config.js:114:35)
sa-demo-cyclops-kibana    |     at Config.set (/usr/share/kibana/src/server/config/config.js:84:10)
sa-demo-cyclops-kibana    |     at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:57:10)
sa-demo-cyclops-kibana    |     at /usr/share/kibana/src/server/plugins/plugin_collection.js:19:12
sa-demo-cyclops-kibana    |     at next (native)
sa-demo-cyclops-kibana    |     at step (/usr/share/kibana/src/server/plugins/plugin_collection.js:49:191)
sa-demo-cyclops-kibana    |     at /usr/share/kibana/src/server/plugins/plugin_collection.js:49:361
sa-demo-cyclops-kibana    |   isJoi: true,
sa-demo-cyclops-kibana    |   name: 'ValidationError',
sa-demo-cyclops-kibana    |   details:
sa-demo-cyclops-kibana    |    [ { message: '"secureCookies" must be a boolean',
sa-demo-cyclops-kibana    |        path: 'xpack.security.secureCookies',
sa-demo-cyclops-kibana    |        type: 'boolean.base',
sa-demo-cyclops-kibana    |        context: [Object] } ],
sa-demo-cyclops-kibana    |   _object:
sa-demo-cyclops-kibana    |    { pkg:
sa-demo-cyclops-kibana    |       { version: '5.5.1',
sa-demo-cyclops-kibana    |         branch: '5.x',
sa-demo-cyclops-kibana    |         buildNum: 15405,
sa-demo-cyclops-kibana    |         buildSha: '32ff80dbccdff23911015425bfaf4ae32ea0c0c1' },
sa-demo-cyclops-kibana    |      dev: { basePathProxyTarget: 5603 },
sa-demo-cyclops-kibana    |      pid: { exclusive: false },
sa-demo-cyclops-kibana    |      cpu: { cgroup: [Object] },
sa-demo-cyclops-kibana    |      cpuacct: { cgroup: [Object] },
sa-demo-cyclops-kibana    |      server:
sa-demo-cyclops-kibana    |       { name: 'kibana',
sa-demo-cyclops-kibana    |         host: '0.0.0.0',
sa-demo-cyclops-kibana    |         port: 5601,
sa-demo-cyclops-kibana    |         maxPayloadBytes: 1048576,
sa-demo-cyclops-kibana    |         autoListen: true,
sa-demo-cyclops-kibana    |         defaultRoute: '/app/kibana',
sa-demo-cyclops-kibana    |         basePath: '',
sa-demo-cyclops-kibana    |         ssl: [Object],
sa-demo-cyclops-kibana    |         cors: false,
sa-demo-cyclops-kibana    |         xsrf: [Object] },
sa-demo-cyclops-kibana    |      logging:
sa-demo-cyclops-kibana    |       { silent: false,
sa-demo-cyclops-kibana    |         quiet: false,
sa-demo-cyclops-kibana    |         verbose: false,
sa-demo-cyclops-kibana    |         events: {},
sa-demo-cyclops-kibana    |         dest: 'stdout',
sa-demo-cyclops-kibana    |         filter: {},
sa-demo-cyclops-kibana    |         json: true },
sa-demo-cyclops-kibana    |      ops: { interval: 5000 },
sa-demo-cyclops-kibana    |      plugins: { scanDirs: [Object], paths: [], initialize: true },
sa-demo-cyclops-kibana    |      path: { data: '/usr/share/kibana/data' },
sa-demo-cyclops-kibana    |      optimize:
sa-demo-cyclops-kibana    |       { enabled: true,
sa-demo-cyclops-kibana    |         bundleFilter: '!tests',
sa-demo-cyclops-kibana    |         bundleDir: '/usr/share/kibana/optimize/bundles',
sa-demo-cyclops-kibana    |         viewCaching: true,
sa-demo-cyclops-kibana    |         lazy: false,
sa-demo-cyclops-kibana    |         lazyPort: 5602,
sa-demo-cyclops-kibana    |         lazyHost: 'localhost',
sa-demo-cyclops-kibana    |         lazyPrebuild: false,
sa-demo-cyclops-kibana    |         lazyProxyTimeout: 300000,
sa-demo-cyclops-kibana    |         useBundleCache: true,
sa-demo-cyclops-kibana    |         profile: false },
sa-demo-cyclops-kibana    |      status: { allowAnonymous: false, v6ApiFormat: false },
sa-demo-cyclops-kibana    |      map: { manifestServiceUrl: 'https://catalogue.maps.elastic.co/v1/manifest' },
sa-demo-cyclops-kibana    |      tilemap: { options: [Object] },
sa-demo-cyclops-kibana    |      regionmap: {},
sa-demo-cyclops-kibana    |      uiSettings: { enabled: true },
sa-demo-cyclops-kibana    |      i18n: { defaultLocale: 'en' },
sa-demo-cyclops-kibana    |      xpack:
sa-demo-cyclops-kibana    |       { xpack_main: [Object],
sa-demo-cyclops-kibana    |         graph: [Object],
sa-demo-cyclops-kibana    |         monitoring: [Object],
sa-demo-cyclops-kibana    |         reporting: [Object],
sa-demo-cyclops-kibana    |         security: [Object] } },
sa-demo-cyclops-kibana    |   annotate: [Function] }
sa-demo-cyclops-kibana exited with code 1

Any ideas?  This is with Kibana 5.6.3.

**Comment by ctindel** [comment]
Some stackexchange link had me trying double dollar signs when other things weren't working.  I think maybe I was missing the enclosing quotes when using single dollar signs but I can confirm that this works:

XPACK_SECURITY_SECURECOOKIES: "${XPACK_SECURITY_SECURECOOKIES:-false}"

**Comment by ctindel** [comment]
I should also note that you need at least compose 2.1 format to do that kind of interpolation with defaults
